### PR TITLE
To make it work on Windows too (tested with PowerShell)

### PR DESCRIPTION
**Pull request by dpshelio**
This is a test I'm doing. So far I either need to depnd on `psutil` or run a command as shown in [this stackoverflow question](https://stackoverflow.com/questions/37394484/how-do-i-detect-if-my-python-code-is-running-in-powershell-or-the-command-prompt).
It uses [`Start-Transcript`](https://docs.microsoft.com/en-gb/powershell/module/Microsoft.PowerShell.Host/Start-Transcript?view=powershell-5.1).

### CODE REVIEW

**Comment by vitorbaptista** [comment]
Cool! Windows support is the most useful feature still missing on Shellshare. Does this work already?

**Comment by dpshelio** [comment]
It does now... but it's not as good as what `script` does. It's not realtime, it's only when you execute a command. Also, for some reasons, some outputs are working sometimes and not showing on others. :shrug: 
As it's know it requires `psutil` which needs to be installed, so the "short" how to use it would be not that short... but something like:

```shell
# Install python
pip install psutil
wget -OutFile shellshare https://get.shellshare.net
python shellshare
```

And I'm thinking now...  as it is it also requires `psutil` to non Windows... so I may have to rethink the logic.

**Comment by dpshelio** [comment]
With @mikerenfro's help I've got it working the original one on gitbash. I've added the info on [the wiki](https://github.com/vitorbaptista/shellshare/wiki/gitbash). I'll keep working on the PS after I run the next workshop.

**Comment by vitorbaptista** [comment]
Hey @dpshelio, sorry for the delay. Is this ready to be merged? As I can't test it, I'm not sure if there's anything missing. LGTM.

**Comment by vitorbaptista** [comment]
We now support Windows without Cygwin, thanks to @mikerenfro's PR https://github.com/vitorbaptista/shellshare/pull/63

**Comment by edmundlaugasson** [comment]
[Cannot get shellshare 1.1.0 to work under MS Windows 10 :(](https://github.com/vitorbaptista/shellshare/issues/68#issuecomment-789043450)

**Pull request closed without merging**
